### ISSUE TITLE
How to install the models package?

### ISSUE THREAD

**Issue by YLiu-creator** [xhu248/cond_ddpm_wsss#2]
/home/liuyang/anaconda3/envs/WeaklyCloudDetection/bin/python /home/liuyang/pyCharmProject/DiffusionModel/cond_ddpm_wsss-main/scripts/train_tumor_ddfm.py
Traceback (most recent call last):
  File "/home/liuyang/pyCharmProject/DiffusionModel/cond_ddpm_wsss-main/scripts/train_tumor_ddfm.py", line 12, in <module>
    from improved_diffusion.script_util import (
  File "/home/liuyang/pyCharmProject/DiffusionModel/cond_ddpm_wsss-main/improved_diffusion/script_util.py", line 7, in <module>
    from .nnformer_diffusion import nnFormer
  File "/home/liuyang/pyCharmProject/DiffusionModel/cond_ddpm_wsss-main/improved_diffusion/nnformer_diffusion.py", line 7, in <module>
    from models.neural_network import SegmentationNetwork
ModuleNotFoundError: No module named 'models'

I face a problem about the ./improved_diffusion/nnformer_diffusion.py file:
    from models.neural_network import SegmentationNetwork
ModuleNotFoundError: No module named 'models'

**Comment by Liuhm0710** [comment]
I also face this quesion. i tried with pip but could not install, use the interpreter in Pycharm to install models package also failed

**Comment by Liuhm0710** [comment]
@YLiu-creator  @xhu248  Hello i wonder whether the quesion above has been resolved or maybe give me some advice, thanks alot
